Fix bug 1691805: Do not make requests to MT services if locale not supported
mozilla/pontoon pull request #1862
Opened 2021-02-09 21:27 UTC by mathjazz

We're getting lots of 400 errors:
https://bugzilla.mozilla.org/show_bug.cgi?id=1691805

2021-02-10 22:43 UTC, mathjazz commented
@Pike r pretty please?

2021-02-11 11:49 UTC, Pike requested changes
I wish this stuff worked differently, but that's also out of scope, I guess. If we'd eventually chain the MT engines server-side, we'd send the original locale code, and not the custom one. And then bridge that gap on the server side.

I think the frontend changes are OK, but the python parts bother me.

2021-02-11 11:49 UTC, Pike commented on pontoon/machinery/views.py
> +    ):
Now that we only allow these requests for logged-in users, this query lost its purpose. I think we should just remove them.

2021-02-11 11:49 UTC, Pike commented on pontoon/machinery/views.py
> +    locale = Locale.objects.get(systran_translate_code=locale_code)
This could be ambiguous?

2021-02-12 11:51 UTC, mathjazz commented
I've addressed comments in https://github.com/mozilla/pontoon/pull/1862/commits/f654924aa8c08785e18ec31c7dc17eb5ddc3fa33 and https://github.com/mozilla/pontoon/pull/1862/commits/cffb0ea6368a5e070fd01d813c4bd481e05c1147.

In between I've made an additional refactoring.

2021-02-12 13:27 UTC, Pike approved these changes
Thanks, this makes more sense now :-)

2021-02-12 13:41 UTC, merged