Avoid using calc(A + Npx) to circumvent bug in a CSS compressor
mozilla/pontoon pull request #1868
Opened 2021-02-11 20:56 UTC by mathjazz

The + and - operators in CSS calc() must be surrounded by whitespace:
https://developer.mozilla.org/en-US/docs/Web/CSS/calc()#notes

The yuglify CSS compressor we use removes them and breaks CSS.
I tried yuicompressor instead, which has the same bug:
https://github.com/yui/yuicompressor/issues/59

Other CSS compressors I've checked look (even more) outdated.
I haven't tested any.

The only other instance of calc() in our code uses - instead of +,
which is fine.

2021-02-11 22:55 UTC, Pike commented
I mentioned this on matrix, I don't think we should constrain our CSS by bugs in that pipeline. In particular for CSS, where there's just not much to win, IMHO.

https://django-pipeline.readthedocs.io/en/latest/compressors.html#no-op-compressors suggests that we can just use a no-op css compressor to cat the files together.

If we're really concerned, maybe there's a trick to compress the cat'ed css files with a transfer encoding.

2021-02-11 23:29 UTC, mathjazz commented
> https://django-pipeline.readthedocs.io/en/latest/compressors.html#no-op-compressors suggests that we can just use a no-op css compressor to cat the files together.

Agreed. I've tested this on stage and it works as expected.

2021-02-11 23:35 UTC, Pike requested changes

2021-02-11 23:35 UTC, Pike commented on pontoon/settings/base.py
> +    "CSS_COMPRESSOR": "pipeline.compressors.terser.NoopCompressor",
That one doesn't exist, it's in the parent, https://github.com/jazzband/django-pipeline/blob/master/pipeline/compressors/__init__.py#L256

Weird that that does something constructive on stage

2021-02-12 08:33 UTC, Pike approved these changes

2021-02-12 08:34 UTC, julen approved these changes
I fully agree with Axel. Changes look good to me 👍.

2021-02-12 09:15 UTC, merged