Fix bug 1713058: Only set target-language if not set
mozilla/pontoon pull request #2009
Opened 2021-09-03 12:50 UTC by mathjazz

The original bug report was to avoid updating values in the `target-language` attribute for non-iOS projects. As per the discussion in l10n-community on Matrix, we've decided to go a step further and never update the `target-language` attribute. We only set it, if it's not set yet.

2021-09-09 17:06 UTC, Pike reviewed
So, the intent is that if the file is tagged as `de`, but in the `fr` locale, it stays tagged as `de`?

Would force-sync change anything here?

Also, I had a hard time figuring out the differences between the tests, some more detailed comments would be good.

2021-09-09 18:46 UTC, mathjazz commented
We're solving two issues with this patch:

1. Pontoon doesn't set `target-language` attribute if it's not set, but our iOS projects require it.

2. Pontoon rewrites `target-language` attributes and in return [fights with automation](https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/pull/153/files).

Force-sync would not change anything. Simply changing the logic to set attributes does not trigger a commit - for that we need translation changes.

2021-09-09 19:00 UTC, mathjazz commented
I've updated the `test_save_basic` a little to make it easier to digest that it's not changing the attribute.

Only `test_save_target_language` is.

2021-09-09 20:46 UTC, Pike requested changes
I think this could use some better tests. And maybe a more thorough commit message?

Also, does this mean that we could drop https://github.com/mozilla/pontoon/blob/3f4565dcfd923048db16ca23f382cadc1d497efb/pontoon/sync/formats/xliff.py#L108 now?

2021-09-09 20:46 UTC, Pike commented on pontoon/sync/tests/formats/test_xliff.py
>          Test saving changes to an entity with a single translation.
Adjust the comment here to highlight that the `target-language` attribute exists?

Not sure, should this test actually test that we're not modifying the in-file locale code? That is, not use `self.locale.code`, at least not w/out a suffix?

2021-09-09 20:46 UTC, Pike commented on pontoon/sync/tests/formats/test_xliff.py
> +        Test if the target-language attribute is set.
Maybe: Test that the target-language attribute is set if not present.

2021-09-09 23:35 UTC, mathjazz commented
I've updated the tests a little bit by adding more explicit comments and flipping the state of the `target-language` attribute on the `input_string`.

We still need that [iOS locale code map](https://github.com/mozilla/pontoon/blob/3f4565dcfd923048db16ca23f382cadc1d497efb/pontoon/sync/formats/xliff.py#L108) for now (in case files for these locales are added by Pontoon), although @st3fan mentioned we might be able to use Pontoon-style locale codes in iOS projects soon. Not sure if he has any updates yet?

2021-09-10 12:46 UTC, Pike approved these changes
Thanks, LGTM.

2021-09-10 12:48 UTC, merged