Add script to generate source-only repos for Thunderbird and Seamonkey
mozilla/pontoon pull request #2656
Opened 2022-11-08 23:43 UTC by mathjazz

This script uses https://hg.mozilla.org/projects/comm-l10n/ repository to create repositories with source strings only for Thunderbird and Seamonkey.

It's a standalone script, rather than being included in `mozilla-en-US.py`former, because the latter will be obsolete and removed soon. Mobile has been long gone, Firefox can just use https://hg.mozilla.org/l10n/gecko-strings/, and this script will cover Thunderbird (including Lightning) and Seamonkey.

2022-11-08 23:53 UTC, mathjazz commented
@flodolo I figured you like scripting, so...

2022-11-09 08:51 UTC, flodolo requested changes
I confess I'm not a fan of this script, mostly because it looks like a very old script with some logic jumps.

Here's an alternative version with some changes in logic, although the general flow remains the same.
https://gist.github.com/flodolo/52cdf68eb5019a75460df8172efdf957

I'm not super happy about checking the output of `hg status` to see if there's something to commit, but it doesn't look like hg provides any better way. In case, we could commit and push all the time like the previous script was doing 🤷🏼 

If you feel strongly about keeping something similar to what we already have, at least we should pass it through black.

2022-11-09 08:51 UTC, flodolo commented on bin/make_comm_source_repos.py
> +    for subdir in os.listdir(target):
This fails is there is a file in the root…

2022-11-09 11:32 UTC, mathjazz commented
Admittedly, I wanted to stay away from the refactor here, because this is not a long-term solution and refactors always increase risk. Yes, the code is old and ugly, but OTOH didn't require a meaningful update in over 4 years.

However, the script you proposed is much more modern, so I'm happy to take it.
Especially considering you'll now own it. 😛

2022-11-09 11:39 UTC, flodolo approved these changes
I knew it…

![star-wars-its-a-trap](https://user-images.githubusercontent.com/3644868/200820936-f9c21397-7658-4b90-842e-b48397905cc4.gif)

2022-11-09 11:44 UTC, merged