Add ability to opt-out of access key localization
mozilla/pontoon pull request #2847
Opened 2023-05-11 09:53 UTC by mathjazz

This patch adds the ability for locales to opt-out of access key localization. For such locales, pretranslation keeps the accesskeys unchanged.

2023-05-11 10:04 UTC, mathjazz commented on pontoon/pretranslation/pretranslate.py
> +            and len(node.value.elements[0].value) <= 1
This part of the check is taken from the frontend:
https://github.com/mathjazz/pontoon/blob/2717-accesskey-opt-out/translate/src/modules/translationform/components/TranslationForm.tsx#L49

2023-05-11 11:36 UTC, eemeli requested changes
In principle this looks fine, but we need to figure out what's happening with #2837 until we land further changes in `pontoon/pretranslation/`.

2023-05-16 17:52 UTC, eemeli requested changes

2023-05-16 17:52 UTC, eemeli commented on pontoon/pretranslation/transformer.py
> +            and len(node.value.elements[0].value) <= 1
This condition is either insufficient or too strict; we've plenty of accesskeys that are selectors on `PLATFORM()`. For example: https://pontoon.mozilla.org/en-GB/firefox/browser/browser/menubar.ftl/?string=220792

Given that this is gated on `accesskey_localization` which defaults to `True`, I don't think we need to look at the `.accesskey` value if the flag is set to `False`.

2023-05-16 17:52 UTC, eemeli commented on pontoon/pretranslation/transformer.py
> +    locale. All other Placeables are serialised as TextElements.
```suggestion
    locale.
```

Fixing my own mistake here. Nothing happens to the placeables in this transform.

2023-05-16 18:36 UTC, eemeli approved these changes

2023-05-16 19:14 UTC, merged