Implement email unsubscribe page
mozilla/pontoon pull request #3237
Opened 2024-05-22 09:08 UTC by mathjazz

Fix #3220: Implement email unsubscribe page.

This patch adds a unique user identifier to existing and new users, and uses it to create personalized unsubscribe links.

2024-05-22 09:10 UTC, mathjazz commented on pontoon/messaging/static/css/email_consent.css
> +
Changes to this file drop the scrollbar on the Email consent page, so they are indirectly related to the issue the patch is fixing.

2024-05-22 12:06 UTC, eemeli requested changes

2024-05-22 12:06 UTC, eemeli commented on pontoon/base/models/user_profile.py
> +    unsubscribe_token = models.UUIDField(default=uuid.uuid4, editable=False)
Given that this is a unique user id, why not call it such?

2024-05-22 12:06 UTC, eemeli commented on pontoon/messaging/templates/messaging/subscribe.html
Is this actually used anywhere, or included just as a parallel for the unsubscribe? If the former, "Unsubscribe again" is weird. If the latter, YAGNI.

2024-05-22 12:20 UTC, mathjazz commented on pontoon/messaging/templates/messaging/subscribe.html
Yeah, this page loads if you click on the "Subscribe again" link on the Unsubscribe page.

2024-05-22 14:52 UTC, eemeli commented on pontoon/messaging/templates/messaging/subscribe.html
Ah, ok, that makes sense.

2024-05-22 14:52 UTC, eemeli approved these changes

2024-05-22 17:08 UTC, mathjazz commented
@bcolsson Could you please verify that this is OK? 

Please see my comment [above](https://github.com/mozilla/pontoon/pull/3237#issue-2309993123) why the UX is different compared to the spec.

This is your unsubscribe link on stage:
https://mozilla-pontoon-staging.herokuapp.com/unsubscribe/17e9d1fa-5593-4427-a0de-1bdc8c2679d0/

2024-05-23 18:56 UTC, bcolsson commented
Thanks @mathjazz - based on our conversation in slack I'll approve this, but this will require approval by legal before we merge.

2024-05-29 22:19 UTC, bcolsson commented
Hi @mathjazz - I got legal approval for the changes in this PR.

2024-05-30 06:40 UTC, merged